### ISSUE TITLE
after 1 epoch, IndexError: Caught IndexError in DataLoader worker process 0.  IndexError: tuple index out of range

### ISSUE THREAD

**Issue by lwflwf1** [zsyOAOA/VDNet#2]
Hi Author,
When I was training the model in the train_simulation.py, i met a problem after 1 epoch.

[Epoch: 1/60] train:4900/5000, lh=-0.54, KLG=++29.14, KLIG=++0.89, mse=2.90e-03, GNorm_D:1.0e+04/2.3e+03, GNorm_S:1.0e+03/2.3e+02, lr=2.0e-04
[Epoch: 1/60] train:5000/5000, lh=-0.55, KLG=++25.93, KLIG=++0.79, mse=2.58e-03, GNorm_D:1.0e+04/1.9e+03, GNorm_S:1.0e+03/6.4e+01, lr=2.0e-04
train: Loss=+5.71e+01, lh=-5.25e-01, KL_Guass=+5.47e+01, KLIG=+2.96e+00, mse=4.456e-03, GNorm_D=1.0e+04/4.5e+03, GNorm_S=1.0e+03/2.2e+02
------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train_simulation.py", line 266, in <module>
    main()
  File "train_simulation.py", line 263, in main
    train_model(net, datasets, optimizer, scheduler, loss_fn)
  File "train_simulation.py", line 138, in train_model
    for ii, data in enumerate(data_loader[phase]):
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\_utils.py", line 385, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\disk_1\Anaconda3\envs\opencv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\disk_1\Tencent\QQfile\VDNet-master\datasets\DenoisingDatasets.py", line 140, in __getitem__
    C = im_gt.shape[2]
IndexError: tuple index out of range

it seems that the test data can't be loaded. I don't konw how to fix this. I'm using the pytorch 1.3 not 1.1, could this be the reason?
please help me with this problem.
Thanks!

**Comment by zsyOAOA** [comment]
Please check the image shape when loading dataset. It seems that you load a gray-level image and can't get its channel number, thus cause an error.
